[package]
name = "baggie"
version = "0.1.1"
edition = "2021"
build = "build.rs"

[dependencies]
eframe = "0.29"
egui = "0.29"
rfd = "0.15"
sha2 = "0.10"
walkdir = "2"
chrono = "0.4"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
